spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cinema
    username: root
    password: root
  jpa:
    hibernate:
        ddl-auto: create
    show-sql: true
  application:
    name: cinema

server:
  port: 8080
