spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cinema?verifyServerCertificate=false&useSSL=false&requireSSL=false
#    url: jdbc:mysql://localhost:3306/cinema
#    username: root
#    password: root
    username: tester
    password: 123456789
  jpa:
    hibernate:
        ddl-auto: create
    show-sql: true
  application:
    name: cinema
  redis:
    host: localhost
    port: 6379
    pool:
      max-idle: 8
      min-idle: 0
      max-active: 8
      max-wait: -1
    password: root

server:
  port: 8000
