spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    #mysql configuration
    url: jdbc:mysql://172.18.69.88:3306/cinema?verifyServerCertificate=false&useSSL=false&requireSSL=false
#    username: root
#    password: root
    username: tester
    password: 123456789
  jpa:
    hibernate:
        ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        search:
          default:
            directory_provider: filesystem
            indexBase: index
  application:
    name: cinema
  #redis configuration
  redis:
    host: 172.18.69.88
    port: 6379
    pool:
      max-idle: 8
      min-idle: 0
      max-active: 8
      max-wait: -1
#    password: root

#server run on this address and this port
server:
  port: 8000

serverAddress: 172.18.69.249
serverPort: 8080